name: Weekly Data Update & Deploy

on:
  schedule:
    - cron: '0 0 * * 1'     # Every Monday at 00:00 UTC (03:00 Europe/Rome)
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Run Scopus/Scholar Update
        env:
          SCO_API_KEY:   ${{ secrets.SCO_API_KEY }}
          UNFI_USERNAME: ${{ secrets.UNFI_USERNAME }}
          UNFI_PASSWORD: ${{ secrets.UNFI_PASSWORD }}
        run: |
          python python/scoups_update_db.py

      - name: Run SerpAPI Scholar Update
        env:
          SCHOLAR_USER_ID: ${{ secrets.SCHOLAR_USER_ID }}
          SERPAPI_KEY:     ${{ secrets.SERPAPI_KEY }}
        run: |
          python python/scholar_update.py

      - name: Commit changes
        run: |
          git config --local user.name 'raffaelemazziotti'
          git config --local user.email "${{ secrets.MY_EMAIL }}"
          git add data/ sections/
          git commit -m "Automated weekly data refresh" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: ${{ github.ref }}
