name: Weekly Data Update & Deploy

on:
  schedule:
    - cron: '0 0 * * 1'     # Every Monday at 00:00 UTC (03:00 Europe/Rome)
  workflow_dispatch:       # Allow manual runs

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Run Scopus/Scholar Update
        env:
          SCO_API_KEY:   ${{ secrets.SCO_API_KEY }}
          UNFI_USERNAME: ${{ secrets.UNFI_USERNAME }}
          UNFI_PASSWORD: ${{ secrets.UNFI_PASSWORD }}
          SERPAPI_KEY:   ${{ secrets.SERPAPI_KEY }}
        run: |
          python python/scoups_update_db.py

      - name: Commit any updated data
        run: |
          git config user.name 'raffaelemazziotti'
          git config user.email "${{ secrets.MY_EMAIL }}"
          git add data/ sections/
          git diff --quiet || git commit -m "Automated weekly data refresh"

      - name: Push changes
        run: git push origin main
